	MyDialogFormat=`WWWDLGED,5.0`
	
	MyDialogCaption=`FamiliesFirst Inc. Agency Policy (%_txt%)`
	MyDialogX=19
	MyDialogY=154
	MyDialogWidth=448
	MyDialogHeight=181
	MyDialogNumControls=3
	
	MyDialog01=`380,164,64,DEFAULT,PUSHBUTTON,DEFAULT,"I Disagree",2`
	MyDialog02=`178,164,64,DEFAULT,PUSHBUTTON,DEFAULT,"I Agree",1`
	MyDialog03=`2,4,14,DEFAULT,VARYTEXT,p1,"p1"`
	MyDialog04=`2,14,14,DEFAULT,VARYTEXT,p2,"p2"`
