MyNagwareDialogFormat=`WWWDLGED,5.0`

MyNagwareDialogCaption=`HAL Smalltalker, Inc. http://shareware.hal-smalltalker.com/winbatch`
MyNagwareDialogX=72
MyNagwareDialogY=90
MyNagwareDialogWidth=379
MyNagwareDialogHeight=235
MyNagwareDialogNumControls=4

MyNagwareDialog01=`98,26,126,DEFAULT,PUSHBUTTON,DEFAULT,"http://shareware.hal-smalltalker.com/winbatch",1`
MyNagwareDialog02=`54,2,52,DEFAULT,STATICTEXT,DEFAULT,"HAL Smalltalker, Inc."`
MyNagwareDialog03=`112,2,66,DEFAULT,STATICTEXT,DEFAULT," - The Premier WinBatch &&"`
MyNagwareDialog04=`180,2,78,DEFAULT,STATICTEXT,DEFAULT," TCP/IP Shareware Publisher"`

ButtonPushed=Dialog("MyNagwareDialog")

